### ISSUE TITLE
Support more arguments

### ISSUE THREAD

**Issue by ribbanya** [winstonpuckett/WinstonPuckett.PipeExtensions#1]
Hi! This looks like a very clean implementation. Thank you for writing it.

In the [repository you reference](https://github.com/TomyDurazno/PipeExtensions/blob/710aea58e21cb3bd1147748990a036a3a65e8dc0/PipeExtensions.cs), up to 25 arguments can be piped at once. Clearly this is overkill (I would never want to look at code that has `.Pipe(A, ..., Z)`) but [`System.Func`](https://docs.microsoft.com/en-us/dotnet/api/system.func-17) for example does support up to 16 arguments.

I prefer your library because of the documentation and `async` support, but would you consider adding more arguments?

Thank you!

---

It seems I misread the other repository's code; it actually allows you to chain multiple functions without subsequent `Pipe` calls. That's not what I'm asking for. I would just like more arguments per function supported.

**Comment by ivy-puckett** [comment]
@ribbanya Thanks for taking the time to write about this! I'm open to having this discussion - I opted for not including multiple arguments as described above because I couldn't think of an elegant syntax which would support ".Pipe" as extensions only work on one argument.

With the current set of features, there are actually multiple ways to pass multiple arguments even though the function you pipe to only accepts one. For instance - 

Tuple Types [reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples):

```csharp
[Fact]
public void NamedTuplesWork()
{
    var person = 
        (name: "Ingrid", age: 10)
        .Pipe(AddOneToAge)
        .Pipe(AddOneToAge)
        .Pipe(AddOneToAge);

    Assert.Equal(13, person.age);
}

private (string name, int age) AddOneToAge((string name, int age) person)
{
    return (person.name, person.age + 1);
}
```

Or if your codebase already exists, you could do an anonymous function and pass in the extra argument from local scope:

```csharp
[Fact]
public void PassingFromScopedWorks()
{
    int stepsTravelled = 0;
    int stepsToAddPerCall = 2;

    var totalSteps = 
        stepsTravelled
        .Pipe(travelled => AddStepsToTotal(travelled, stepsToAddPerCall))
        .Pipe(travelled => AddStepsToTotal(travelled, stepsToAddPerCall))
        .Pipe(travelled => AddStepsToTotal(travelled, stepsToAddPerCall))
        .Pipe(travelled => AddStepsToTotal(travelled, stepsToAddPerCall))
        .Pipe(travelled => AddStepsToTotal(travelled, stepsToAddPerCall));

    Assert.Equal(10, totalSteps);
}

private int AddStepsToTotal(int stepsTravelled, int stepsToAddPerCall)
{
    return stepsTravelled + stepsToAddPerCall;
}
```

Which could also be refactored as a local function if preferred:

```csharp
[Fact]
public void PassingFromScopedWorks_RefactoredAsMonadic()
{
    int stepsTravelled = 0;
    int stepsToAddPerCall = 2;

    int AddStepsToStepsTravelled(int travelled)
        => travelled + stepsToAddPerCall;

    var totalSteps =
        stepsTravelled
        .Pipe(AddStepsToStepsTravelled)
        .Pipe(AddStepsToStepsTravelled)
        .Pipe(AddStepsToStepsTravelled)
        .Pipe(AddStepsToStepsTravelled)
        .Pipe(AddStepsToStepsTravelled);

    Assert.Equal(10, totalSteps);
}
```

Would these fit your use case? I took the time to actually build up these tests and commit them to main, so that it would be a noticeable breaking change if any of these don't work in the future.

**Comment by ribbanya** [comment]
Hi, thanks for taking the time to reply.

Tuples are indeed very useful for this (in fact F# basically converts all calls to C# functions into tuple arguments). I guess that I was just thinking of currying functions in F#, or for a simpler implementation, [piping multiple arguments in Elixir](https://elixirschool.com/en/lessons/basics/pipe-operator/#best-practices), where you can simply add extra arguments in parentheses.

> I opted for not including multiple arguments as described above because I couldn't think of an elegant syntax

In the end, I think this is just a conceit of C# we have to live with. I think we would both prefer a native pipe syntax, but as it stands we are allowed to do this:

```cs
2
.Pipe(DoubleIt) // int DoubleIt(int it) = 2 * 2 = 4
.Pipe(MultiplyBy, 3) // int MultiplyBy(int x, int y) = 4 * 3 = 12
.Pipe(Concat, 4, 5, 6); // int Concat(params int[] values) = 12 + 4 + 5 + 6 = 27
```

It's not the most beautiful code I've ever looked at but it is still very intuitive as to what it is doing.

---

Incidentally, after writing that example I was curious whether it's possible to pipe `params` like that and it absolutely is:

```cs
using System;
using System.Linq;
using NUnit.Framework;

public static class ParamsPipeExtension
{
    public delegate U ParamsDelegate<T, U>(params T[] args);

    public static U Pipe<T, U>(this T value, ParamsDelegate<T, U> func, params T[] otherArgs)
    {
        var combinedArgs = new T[otherArgs.Length + 1];
        combinedArgs[0] = value;
        Array.Copy(otherArgs, 0, combinedArgs, 1, otherArgs.Length);
        return func(combinedArgs);
    }
}

public sealed class ParamsPipeTests
{
    [Test]
    public void CanPipeStuff()
    {
        static int Concat(params int[] values) => values.Sum();

        var x = 2.Pipe(Concat, 3, 4, 5);
        Assert.AreEqual(14, x);
    }
}
```

**Comment by ivy-puckett** [comment]
Oh, I see! So you could pass the function, then extra parameters... I totally agree that a native pipe syntax would be better than anything we could do. I'm thinking that I want to encourage the tuple syntax over params. In the above example, I think it would be as easy to pass an int array as one parameter vs passing a function with a listed out int array? Any thoughts on that?

In general, I want to encourage the use of monadic functions as they seem to be a goal for both Functional and OOP paradigms (I tried to get Uncle Bob's actual quote, but here's a blog post about it at least - [post](https://www.matheus.ro/2018/01/29/clean-code-avoid-many-arguments-functions/#:~:text=Uncle%20Bob%20%28Robert%20C.%20Martin%29%2C%20in%20the%20Clean,arguments%20%28triadic%20function%29%20should%20be%20avoided%20if%20possible.)). When a monadic function can't be used, having something where the caller is forced to write something extra, as long as it's still elegant, calls out a place where a refactor _might_ be performed.

I also feel like having a clear delineation of "you always look to the left of the dot for what gets passed in and to the right of the dot for what it gets passed to" reduces read time. My example above of a local function violates this principle, so maybe tuples would be the best way...

I'm writing as if my mind's made up, but it's more of a leaning. If we can find a strong case for when this would be the best/most readable syntax I'm still open to adding this sort of thing.

**Comment by ribbanya** [comment]
I do agree with Bob about that in general ([here's](https://youtu.be/7EmboKQH8lM?t=4240) the quote you want, probably). I've been leaning my codebases more and more toward monads lately, with a fluent API if possible.

The thing is, the `Pipe` extension method isn't so much an actual operator as it is a way of using non-fluent APIs in a fluent manner, within the limitations of C#. Most of the time, these APIs are not from your own codebase. If I'm writing my own code anyway, I can just use extension methods in the first place:

```cs
public static (string name, int age) AddOneToAge(this (string name, int age) person) => (person.name, person.age + 1);

public static readonly (string name, int age) ThirteenYearsOld =
    ("Ingrid", 10)
    .AddOneToAge()
    .AddOneToAge()
    .AddOneToAge();
```

Consider [`DateTime.Parse`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=net-5.0#System_DateTime_Parse_System_String_System_IFormatProvider_). You could write a wrapper around it, or use a lambda, but the benefit of using a `Pipe` extension is that you don't have to:
```cs
var provider = CultureInfo.CreateSpecificCulture("en-US");
var fourDaysFromThen =
    "01/10/2009 7:34 PM"
    .Pipe(DateTime.Parse, provider)
    .Add(TimeSpan.FromDays(4))
    .ToString(provider);
```

---

Thought of a more elaborate example. Often I use static reflection during startup for more flexible code, or to access non-public APIs in a framework I'm using, etc. This example is contrived, of course, but I do similar things pretty regularly.

```cs
const BindingFlags bindingFlags = BindingFlags.NonPublic | BindingFlags.Instance;
var relevantInterfaceType = typeof(SomePublicInterfaceFromSomeFramework<>);
var instance = 
    relevantInterfaceType
    .Assembly
    .GetTypes()
    .Where(t => t.IsClass)
    .Where(t => !t.IsAbstract)
    .First(t => t.IsAssignableTo(relevantInterfaceType))
    .GetProperty("SomePrivatePropertyName", bindingFlags)
    .Pipe(pi => pi!.PropertyType)
    .Pipe(Activator.CreateInstance, bindingFlags, null, null, null)
    .Pipe(o => (MyPropertyInstance) o!);
```
Without multi-argument `Pipe`:
```cs
//  .Pipe(pi => pi!.PropertyType)
    .Pipe(t => (MyPropertyInstance) Activator.CreateInstance(t, bindingFlags, null, null, null)!)
```
Note how easy it is to visually lose track of what's actually being passed in. And being unable to use multi-argument `Pipe` encourages putting the cast and null forgiveness in the same lambda as `Activator.CreateInstance`, when it's much more readable if they're separate.

Note also that this is *not* a snippet of code that goes in a public function. It's doing really low-level stuff and would be called a few levels below the public API. But `Pipe` with extra arguments is still very useful and allows you to forego writing a helper method without sacrificing any readability.

**Comment by ivy-puckett** [comment]
The third party library argument is pretty compelling. I'm going to have to think about this. I've always thought of Pipe as a higher level concept than for an operation - to be used in a paragraph vs a sentence if you will. Hearing the use case of "Pipe for a lower level operation" is something surprising. I'll try to respond to this in the next couple days after thinking about it.

Also that's the exact quote I was looking for 😃

**Comment by ivy-puckett** [comment]
Hi @ribbanya, I've tried to justify this in my head over the past week. It feels to me like it encourages something which the package wasn't entirely intended for... The "using .Pipe with an external API" is a really compelling argument, but I went back to Linq and looked at how/if they allow this sort of thing and it looks like they only allow multiple arguments when there is a specific operation like Joining.

With Linq's .Select() for instance, you can only pass in the IEnumerable and the index. If you want to pass multiple arguments, you'd have to use one of the methods we've described above. - https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?view=net-5.0

Because tuples, and the other solutions we've found, enable us to pass multiple arguments in a group, I am going to leave the package as is.

This discussion made me realize there's no argument for the CancellationToken, which is an extra argument which will be included in a 1.1.0 release.

I really appreciate you taking the time to write about this. I'm very grateful for your clear communication of the issue and that you have felt enough interest in the package to raise an issue. I look forward to hearing your good ideas in the future.

**Comment by ivy-puckett** [comment]
Hi @ribbanya, I don't think this will quite solve your use case from above, but I kept thinking about this issue, and eventually decided to implement a version of this. Because I'm trying to follow closely with F# and F# enables monadic, dyadic, and triadic functions, I looked into how I might do that.

With version 1.3.0, you can now use a tuple on the left (with two or three arguments) and .Pipe will destructure the tuple to the function on the right.

```csharp
bool returnTrue(int _, string _2) => return true;

var result = (0, string.Empty).Pipe(returnTrue);

Assert.True(result);
```

I hope your day is going well and this is exciting news instead of noise. Thank you again for your interest in this package.

**Comment by ribbanya** [comment]
Oh, nice! Thanks for letting me know!
